[package]
name = "rustbug"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
clap = { version = "4.5.29", features = ["cargo"] }
colored = "2.2.0"
crossterm = "0.28.1"
serialport = "4.6.0"
